name: book-cli-with-ssh

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: ssh deploy
        uses: easingthemes/ssh-deploy@v2.2.11
        with:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USERNAME }}
          REMOTE_PORT: 22
          SOURCE: ./
          TARGET: /home/temp_doc/
      - name: executing remote ssh commands using ssh key
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USERNAME }}
            key: ${{ secrets.DEPLOY_KEY }}
            port: 22
            script: |
              mdbook -V
              ls /home/temp_doc
              cd /home/temp_doc && mdbook clean && mdbook build
              rm -rf /www/wwwroot/doc.springcloud.io/*
              mv /home/temp_doc/book/*  /www/wwwroot/doc.springcloud.io/
              rm -rf /home/temp_doc/*


